export const zh = {
  defaultConversationTitle: 'ChatGPT 对话',
  userExportRole: '用户',
  assistantExportRole: 'ChatGPT',
  userRole: '我',
  assistantRole: 'ChatGPT',
  openNavigator: '打开 ChatPilot',
  closeNavigator: '关闭 ChatPilot',
  navigatorLabel: 'ChatPilot 对话导航',
  searchMessages: '搜索消息',
  searchPlaceholder: '搜索对话内容',
  selectionControls: '选择控制',
  selectAll: '全选',
  clear: '清除',
  userOnly: '仅我的消息',
  assistantOnly: '仅 ChatGPT 消息',
  userNavigation: '我的消息导航',
  status: 'ChatPilot 状态',
  previousUser: '上一条我的消息',
  nextUser: '下一条我的消息',
  discoveredMessages: '已发现的消息',
  selectMessage: '选择',
  goToMessage: '跳转到',
  emptyMessage: '空消息',
  noConversation: '请先打开一个 ChatGPT 对话。',
  noSearchResults: '没有匹配的消息。',
  loadConversation: '加载完整对话',
  reindexConversation: '重新索引当前对话',
  cancel: '取消',
  working: '正在处理…',
  exportConversation: '导出对话',
  exportFormat: '格式',
  exportScope: '范围',
  export: '导出',
  allMessages: '全部消息',
  assistantMessages: '仅 ChatGPT 消息',
  selectedMessages: '已选消息',
  selectOneMessage: '请至少选择一条消息。',
  popupSubtitle: '会话导航与导出',
  navigatorEnabled: '启用导航器',
  navigatorEnabledHint: '在 ChatGPT 页面显示会话导航栏。',
  smoothScroll: '平滑滚动',
  smoothScrollHint: '跳转到消息时使用平滑动画。',
  defaultExportFormat: '默认导出格式',
  defaultExportScope: '默认导出范围',
  navigatorWidth: '导航栏宽度',
  settingsLoadError: '无法加载设置，请重新打开弹窗后重试。',
  settingsSaveError: '无法保存设置，请重试。',
  loading: '正在加载…',
  saving: '正在保存…',
  saved: '已保存',
  privacyNote: 'ChatPilot 仅在浏览器本地处理对话内容，不会将你的对话发送到外部服务。',
} as const;
